### ISSUE TITLE
Can i get dataset used to train tamil-llama? 

### ISSUE THREAD

**Issue by bharathdpv** [abhinand5/tamil-llama#6]
Hello abhinand5, iam bharath kumar currently researching about local llm. I have a plan to fine tune the model based on civil construction. training dataset will be helpfull!. So I can train/finetune the model from scratch in tamil language.thanks 

Regards, 
Bharath kumar

**Comment by abhinand5** [comment]
The pretraining dataset was taken from [CulturaX](https://huggingface.co/datasets/uonlp/CulturaX)

```python
from datasets import load_dataset

ds = load_dataset("uonlp/CulturaX", "ta",
    use_auth_token=True,
    split="train",
    streaming=True,
    token=hf_token,
    revision="321a983f3fd2a929cc1f8ef6207834bab0bb9e25"
)
```

The finetuning datasets are already linked in the README

https://github.com/abhinand5/tamil-llama?tab=readme-ov-file#datasets

**Comment by bharathdpv** [comment]
thank you!
