### ISSUE TITLE
Issue resuming checkpoint while pretraining

### ISSUE THREAD

**Issue by VishnuPJ** [abhinand5/tamil-llama#7]
Error:
model.load_adapter(resume_from_checkpoint, model.active_adapter, is_trainable=Tue)
TypeError: PeftAdapterMixin.load_adapter() got an unexpected keyword argument 'is_tainable'

I have installed transformers asd peft as follows,

Custom Transformers Library: Use the transformers library from my clone. This version includes a small but crucial patch that enables resuming pretraining from checkpoints.

pip install git+https://github.com/abhinand5/transformers.git@abhinand5-deepspeed-patch

PEFT Library Version: Install a specific version of the peft library. Recent updates in the peft packages have introduced compatibility issues, and using the specified version helps avoid these problems.

pip install git+https://github.com/huggingface/peft.git@13e53fc

**Comment by abhinand5** [comment]
```
TypeError: PeftAdapterMixin.load_adapter() got an unexpected keyword argument 'is_tainable'
```
That's weird, especially the typo!

I have an active running environment that works fine. Please try that, install `peft` and `transformers` the way I've mentioned.

[environment.txt](https://github.com/abhinand5/tamil-llama/files/13891668/environment.txt)

> Change txt to yaml, looks like yaml upload isn't supported in GitHub
